{{- include "crd-schema-publisher.validateNetworkPolicy" . -}}
{{- $hasBaseIngress := eq .Values.mode "controller" -}}
{{- $hasExtraIngress := not (empty .Values.ciliumNetworkPolicy.extraIngress) -}}
{{- $hasIngress := or $hasBaseIngress $hasExtraIngress -}}
{{- $hasEgress := not (empty .Values.ciliumNetworkPolicy.extraEgress) -}}
{{- if and .Values.ciliumNetworkPolicy.enabled (or $hasIngress $hasEgress) -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "crd-schema-publisher.fullname" . }}
  labels:
    {{- include "crd-schema-publisher.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "crd-schema-publisher.selectorLabels" . | nindent 6 }}
  {{- if $hasIngress }}
  ingress:
    {{- if $hasBaseIngress }}
    # Metrics scraping and helm test hook
    - toPorts:
        - ports:
            - port: {{ .Values.config.healthPort | quote }}
              protocol: TCP
    {{- end }}
    {{- with .Values.ciliumNetworkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $hasEgress }}
  egress:
    {{- toYaml .Values.ciliumNetworkPolicy.extraEgress | nindent 4 }}
  {{- end }}
{{- end }}
