{{- if .Values.serve.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "crd-schema-publisher.fullname" . }}
  labels:
    {{- include "crd-schema-publisher.labels" . | nindent 4 }}
    {{- with .Values.serve.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serve.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.serve.httpRoute.parentRefs | nindent 4 }}
  {{- with .Values.serve.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- with .Values.serve.httpRoute.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serve.httpRoute.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "crd-schema-publisher.fullname" . }}
          port: {{ .Values.serve.port }}
{{- end }}
