{{- if and .Values.rbac.create (eq .Values.mode "controller") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crd-schema-publisher.fullname" . }}-leader-election
  labels:
    {{- include "crd-schema-publisher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
{{- end }}
